all: bidding_system.c host.c player.c player_bonus.c
	gcc -O3 bidding_system.c -o bidding_system
	gcc -O3 host.c -o host
	gcc -O3 player.c -o player
	gcc -O3 player_bonus.c -o player_bonus
clean:
	rm -f bidding_system host player player_bonus
